### ISSUE TITLE
Is it still working? 

### ISSUE THREAD

**Issue by AlexBlack009** [sg-dev1/Video_Stream_Player#1]
Is it still working and can it play 1080p. I tried to setup it but failed setting it up for testing purposes.

**Comment by sg-dev1** [comment]
Doing a fast investigation it seems that the Licence Request to Amazon failed.
It returned the following error:
"errorsByResource": {
        "Widevine2License": {
            "downstreamReason": "vmp_validation_required",
            "errorCode": "PRS.Dependency.DRM.Widevine.HdContentNotAllowed.VmpValidationRequired",
            "message": "Cannot complete request.",
            "type": "PRSWidevine2LicenseDeniedException"
        }
    },

When searching for this vmp_validation_required it seems that the guys at Kodi have a similar issue:
https://forum.kodi.tv/showthread.php?tid=342716
https://forum.kodi.tv/showthread.php?tid=331136&pid=2841979#pid2841979
"Google enforced VMP validation, in order to do that Kodi and all the relative binaries must be certified by Google. "

Before that 1080p was working, at least on a normal desktop PC. On the Raspberry Pi 3 the performance was too poor.

**Comment by sg-dev1** [comment]
To get it running under Linux in SD you could comment out lines 207 and 208 of amazon.py (https://github.com/sg-dev1/Video_Stream_Player/blob/master/frontend/amazon.py#L207).
Then using `./prime_video_cli -p <ASIN>` you could print out the available resolutions, e.g.:
`
$ ./prime_video_cli -p B00FGLE0TK
[...]
VideoRepresentation( 720 x 480,  mediaFileUrl= [...]
`
And start the stream using `./prime_video_cli -r <RESOLUTION> <ASNI>`, e.g.:
`./prime_video_cli -r 720x480 B00FGLE0TK`.

For me the playback worked, however there was an display issue. So seems there is a bug within the renderer for resolutions other than 1080p.

Hope that helps.

**Comment by AlexBlack009** [comment]
Removed thanks
